Almost complete
TODO: Fix asm.
TileEntityTransformer doesn’t yet work, causing the game to crash with:
java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoClassDefFoundError:
net/minecraft/tileentity/TileEntity
Caused by: java.lang.ClassNotFoundException:
net.minecraft.tileentity.TileEntity
Caused by: java.lang.NullPointerException